name: Build and release App

on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]  # Customize the Python version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install . && pip install pyinstaller

      - name: Build with PyInstaller
        run: cd sim && pyinstaller --onefile --noconsole sim.py

      - name: Zip the binary
        run: |
          cp -r sim/assets dist/assets
          mv dist over_under_sim
        working-directory: ${{ github.workspace }}

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: over_under_sim_${{ matrix.os }}
          path: over_under_sim
